name: Test docker scripts
on:
  pull_request:
    branches: [ main, master ]
  merge_group:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  test_docker:
    name: Run test suite
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Docker build
      run: |
        docker run -d -p 5432:5432 -e POSTGRES_PASSWORD=postgres postgres
        testscr=$(awk '/```docker-run.sh/{f=1;next} /```/{f=0} f' README.md)
        echo $testscr
        eval "$testscr"
    
    - name: Test docker run
      run: sleep 5 && docker ps && curl localhost:3004 | grep -q "Prostgles UI"; echo $?

    - name: Docker stop
      run: docker stop $(docker ps -a -q)

    - name: Docker compose
      run: docker compose up -d

    - name: Test docker compose
      run: sleep 5 && docker ps && curl localhost:3004 | grep -q "Prostgles UI"; echo $?
