name: Electron build windows
on: workflow_dispatch 
jobs:
  electron_build_windows:
    timeout-minutes: 20
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Test 
      shell: cmd
      run: |
        cd electron
        echo %DATE% %TIME%
        dir "C:\Program Files (x86)\"
        curl screenCapture.bat https://github.com/npocmaka/batch.scripts/blob/master/hybrids/.net/c/screenCapture.bat
        waitfor SomethingThatIsNeverHappening /t 10 2>NUL
        screenCapture.bat .\dist\screen.png

    - name: Build
      run: |
        cd electron && npm run build-win

    - name: Test build
      shell: cmd
      run: |
        cd electron
        echo %DATE% %TIME%
        dir "C:\Program Files (x86)\"
        "./dist/Prostgles\ Desktop-1.0.0.exe" --silent
        echo %DATE% %TIME%
        dir "C:\Program Files (x86)\"
        dir "C:\Program Files\"
        dir "C:\Program Files\Prostgles Desktop-1.0.0\"
        "C:\Program Files (x86)\Prostgles Desktop-1.0.0\prostgles-desktop.exe"
        waitfor SomethingThatIsNeverHappening /t 10 2>NUL
        call screenCapture .\dist\screen.png
      
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: installers
        path: electron/dist
        retention-days: 10
